Feat/Add:  jitsi_conference_sizes metric
systemli/prometheus-jitsi-meet-exporter pull request #36
Opened 2021-03-16 10:20 UTC by RafPe

Adds metrics for jitsi_conference_sizes

2021-03-16 10:34 UTC, 0x46616c6b requested changes
Thanks for this contribution. I only have a minor change request regarding the nameing/labels.

2021-03-16 10:34 UTC, 0x46616c6b commented on main.go
> +jitsi_conference_sizes{conferenceSize="{{$key}}"} {{ $value }}
Would suggest to use snake case for Prometheus metrics.

```suggestion
jitsi_conference_sizes{conference_size="{{$key}}"} {{ $value }}
```

2021-03-16 10:34 UTC, 0x46616c6b commented on main.go
> +# HELP jitsi_conference_sizes Conference sizes
```suggestion
# HELP jitsi_conference_sizes Distribution of conference sizes
```

2021-03-16 10:34 UTC, 0x46616c6b commented on main_test.go
> +jitsi_conference_sizes{conferenceSize="21"} 0
```suggestion
# HELP jitsi_conference_sizes Distribution of conference sizes
# TYPE jitsi_conference_sizes gauge
jitsi_conference_sizes{conference_size="0"} 0
jitsi_conference_sizes{conference_size="1"} 1
jitsi_conference_sizes{conference_size="2"} 0
jitsi_conference_sizes{conference_size="3"} 1
jitsi_conference_sizes{conference_size="4"} 0
jitsi_conference_sizes{conference_size="5"} 0
jitsi_conference_sizes{conference_size="6"} 0
jitsi_conference_sizes{conference_size="7"} 0
jitsi_conference_sizes{conference_size="8"} 0
jitsi_conference_sizes{conference_size="9"} 0
jitsi_conference_sizes{conference_size="10"} 0
jitsi_conference_sizes{conference_size="11"} 0
jitsi_conference_sizes{conference_size="12"} 0
jitsi_conference_sizes{conference_size="13"} 0
jitsi_conference_sizes{conference_size="14"} 0
jitsi_conference_sizes{conference_size="15"} 0
jitsi_conference_sizes{conference_size="16"} 0
jitsi_conference_sizes{conference_size="17"} 0
jitsi_conference_sizes{conference_size="18"} 0
jitsi_conference_sizes{conference_size="19"} 0
jitsi_conference_sizes{conference_size="20"} 0
jitsi_conference_sizes{conference_size="21"} 0
```

2021-03-16 10:34 UTC, 0x46616c6b commented on main_test.go
> +jitsi_conference_sizes{conferenceSize="21"} 0
```suggestion
# HELP jitsi_conference_sizes Distribution of conference sizes
# TYPE jitsi_conference_sizes gauge
jitsi_conference_sizes{conference_size="0"} 0
jitsi_conference_sizes{conference_size="1"} 1
jitsi_conference_sizes{conference_size="2"} 0
jitsi_conference_sizes{conference_size="3"} 1
jitsi_conference_sizes{conference_size="4"} 0
jitsi_conference_sizes{conference_size="5"} 0
jitsi_conference_sizes{conference_size="6"} 0
jitsi_conference_sizes{conference_size="7"} 0
jitsi_conference_sizes{conference_size="8"} 0
jitsi_conference_sizes{conference_size="9"} 0
jitsi_conference_sizes{conference_size="10"} 0
jitsi_conference_sizes{conference_size="11"} 0
jitsi_conference_sizes{conference_size="12"} 0
jitsi_conference_sizes{conference_size="13"} 0
jitsi_conference_sizes{conference_size="14"} 0
jitsi_conference_sizes{conference_size="15"} 0
jitsi_conference_sizes{conference_size="16"} 0
jitsi_conference_sizes{conference_size="17"} 0
jitsi_conference_sizes{conference_size="18"} 0
jitsi_conference_sizes{conference_size="19"} 0
jitsi_conference_sizes{conference_size="20"} 0
jitsi_conference_sizes{conference_size="21"} 0
```

2021-03-16 10:36 UTC, RafPe commented
I have applied the suggestions :)

2021-03-16 10:45 UTC, RafPe reviewed
Implemented changes

2021-03-17 08:05 UTC, 0x46616c6b approved these changes

2021-03-17 08:05 UTC, merged