add total participants metrics
systemli/prometheus-jitsi-meet-exporter pull request #55
Opened 2021-09-06 14:12 UTC by mclpfr

2021-09-08 14:48 UTC, xshadow commented
The tests for this PR fail, you have to add tests in main_test.go

2021-09-09 05:57 UTC, mclpfr commented
Hello,
Thank you for your feedback, I updated it.
Best regards

2021-09-09 11:01 UTC, 0x46616c6b requested changes
I added two suggestions to fix the test.

2021-09-09 11:01 UTC, 0x46616c6b commented on main_test.go
> +jitsi_total_participants 20
```suggestion
jitsi_total_participants 18
```

2021-09-09 11:01 UTC, 0x46616c6b commented on main_test.go
> +jitsi_total_participants 20
```suggestion
jitsi_total_participants 2
```

2021-09-09 12:32 UTC, mclpfr commented on main_test.go
> +jitsi_total_participants 20
Thank you, it's fixed

2021-09-09 12:32 UTC, mclpfr commented on main_test.go
> +jitsi_total_participants 20
Thank you, it's fixed

2021-09-09 14:26 UTC, merged